package com.nicecoder.murottal

object AudioList {
    val list = mutableListOf(
        Audio("Al Fatihah", R.raw.al_fatihah),
        Audio("Al-Mujadilah", R.raw.al_mujadilah),
        Audio("Al-Hasyr", R.raw.al_hasyr),
        Audio("Al-Mumtahanah", R.raw.al_mumtahanah),
        Audio("As-Saff", R.raw.as_saff),
        Audio("Al-Jumu'ah", R.raw.al_jumuah),
        Audio("Al-Munafiqun", R.raw.al_munafiqun),
        Audio("At-Tagabun", R.raw.at_tagabun),
        Audio("At-Talaq", R.raw.at_talaq),
        Audio("At-Tahrim", R.raw.at_tahrim),
        Audio("Al-Mulk", R.raw.al_mulk),
        Audio("Al-Qalam", R.raw.al_qalam),
        Audio("Al-Haqqah", R.raw.al_haqqah),
        Audio("Al-Ma'arij", R.raw.al_maarij),
        Audio("Nuh", R.raw.nuh),
        Audio("Al-Jinn", R.raw.al_jinn),
        Audio("Al-Muzzammil", R.raw.al_muzzammil),
        Audio("Al-Muddassir", R.raw.al_muddassir),
        Audio("Al-Qiyamah", R.raw.al_qiyamah),
        Audio("Al-Insan", R.raw.al_insan),
        Audio("Al-Mursalat", R.raw.al_mursalat),
        Audio("An-Naba", R.raw.an_naba),
        Audio("An-Nazi'at", R.raw.an_naziat),
        Audio("'Abasa", R.raw.abasa),
        Audio("At-Takwir", R.raw.at_takwir),
        Audio("Al-Infitar", R.raw.al_infitar),
        Audio("Al-Mutaffifin", R.raw.al_mutaffifin),
        Audio("Al-Insyiqaq", R.raw.al_insyiqaq),
        Audio("Al-Buruj", R.raw.al_buruj),
        Audio("At-Tariq", R.raw.at_tariq),
        Audio("Al-A'la", R.raw.al_ala),
        Audio("Al-Gasyiyah", R.raw.al_gasyiyah),
        Audio("Al-Fajr", R.raw.al_fajr),
        Audio("Al-Balad", R.raw.al_balad),
        Audio("Asy-Syams", R.raw.asy_syams),
        Audio("Al-Lail", R.raw.al_lail),
        Audio("Ad-Duha", R.raw.ad_duha),
        Audio("Al-Insyirah", R.raw.al_insyirah),
        Audio("At-Tin", R.raw.at_tin),
        Audio("Al-'Alaq", R.raw.al_alaq),
        Audio("Al-Qadr", R.raw.al_qadr),
        Audio("Al-Bayyinah", R.raw.al_bayyinah),
        Audio("Az-Zalzalah", R.raw.az_zalzalah),
        Audio("Al-'Adiyat", R.raw.al_adiyat),
        Audio("Al-Qari'ah", R.raw.al_qariah),
        Audio("At-Takasur", R.raw.at_takasur),
        Audio("Al-'Asr", R.raw.al_asr),
        Audio("Al-Humazah", R.raw.al_humazah),
        Audio("Al-Fil", R.raw.al_fil),
        Audio("Quraisy", R.raw.quraisy),
        Audio("Al-Ma'un", R.raw.al_maun),
        Audio("Al-Kausar", R.raw.al_kausar),
        Audio("Al-Kafirun", R.raw.al_kafirun),
        Audio("An-Nasr", R.raw.an_nasr),
        Audio("Al-Lahab", R.raw.al_lahab),
        Audio("Al-Ikhlas", R.raw.al_ikhlas),
        Audio("Al-Falaq", R.raw.al_falaq),
        Audio("An-Nas", R.raw.an_nas)
    )
}

data class Audio(val title: String, val resourceId: Int)